//import module
const os = require('os');

//os architecture.............
console.log(os.arch());

//os hostname...........
console.log(os.hostname());

//os free memory............
console.log(os.freemem());

//os total memory...........
console.log(os.totalmem());

//os home directory........
console.log(os.homedir());

//os network interfaces.........
console.log(os.networkInterfaces());

//os platform...............
console.log(os.platform());

//os release...........
console.log(os.release());

//os temporary directory.........
console.log(os.tmpdir());

//os type (windows/mac/linux)............
console.log(os.type());

//os uptime in seconds................
console.log(os.uptime());

//os version.............
console.log(os.version());